export { default as EigenvectorsIcon } from "./EigenvectorsIcon";
export { default as LinearAlgebraIcon } from "./LinearAlgebraIcon";
export { default as MathIcon } from "./MathIcon";
export { default as MatrixMultiplicationIcon } from "./MatrixMultiplicationIcon";
export { default as NormIcon } from "./NormIcon";
export { default as TransformationIcon } from "./TransformationIcon";
export { default as TransposeIcon } from "./TransposeIcon";
export { default as VectorScalingIcon } from "./VectorScalingIcon";
export { default as FitFrameIcon } from "./FitFrameIcon";
